### ISSUE TITLE
Adapting JEM to high-resolution images

### ISSUE THREAD

**Issue by YeeZ93** [wgrathwohl/JEM#14]
Dear Will Grathwohl,

Thanks so much for the inspiring work!  

Now I am trying to adapt your proposed joint energy-based model to more challenging dataset , where resized 256^2 ~ 512^2  images exist. As a result, the JEM does not converge well no matter what regularization methods (L2/L2 grad regularizations as described at https://github.com/wgrathwohl/JEM/issues/4 ) are used. Could you please provide with me some ideas for advancing JEM to high-resolution images?

Thanks in advance,

Best,
Jun-Pu

**Comment by chang-1** [comment]
Hi! Could you share some ideas on how to adapt the code to train on custom sizes? I tried increasing the self.last_dim parameter, but it takes too long to train on one epoch. Do you have any other suggestion? Thanks in advanced.
